### PR TITLE
Change the results strings

### PR DESCRIPTION
**Pull request by MadDoct**
Making the result more usefull to integrate into sensors or switches in home assistant

### CODE REVIEW

**Comment by andrethomas** [comment]
Can be done, but I would prefer to do MCP230XX_SENSOR_RESPONSE change on development branch as it originates from there and the MCP230XX_CMND_RESPONSE can be done to the mcp230xx_output branch.

To better explain, the development branch is derived from arendst;development while the mcp230xx_output branch is derived from andrethomas:development.

I do not want to seperate arendst:development from andrethomas:development

Make sense?

**Comment by andrethomas** [comment]
So technically you could make the MCP230XX_SENSOR_RESPONSE PR directly to https://github.com/arendst/Sonoff-Tasmota

**Comment by MadDoct** [comment]
Ok, but would only change one of the responses and not both

**Comment by andrethomas** [comment]
Both can be changed, just not in the output branch. Change the MCP230XX_SENSOR_RESPONSE in the development branch and the MCP230XX_CMND_RESPONSE in the output branch. When the development branch changes are pulled to the output branch then both changes will be in the output branch.

**Comment by andrethomas** [comment]
If you change it only in the output branch the MCP230XX_SENSOR_RESPONSE change will never make it back to development - currently, I do not push changes in the output branch to the development... not sure how else to explain it :)

**Comment by andrethomas** [comment]
Are you registered on discordapp.com ?

**Comment by andrethomas** [comment]
Or Telegram ? Either of them I can walk you through it - much easier than talking on here...

**Comment by andrethomas** [comment]
I did it the long way round... next time PR for stuf inside #ifdef USE_MCP230xx_OUTPUT to mcp230xx_output branch - stuff not inside the define, PR to development please :)

**Comment by andrethomas** [comment]
And your change to development branch has been committed to the main Tasmota development also...

**Comment by andrethomas** [comment]
About publishing to another topic - I think its best to leave it as is because it's not a device internal to a Sonoff device.

**Comment by MadDoct** [comment]
If I want to do it for myself anyway, will it take a lot of coding? As I told you, my C++ skills are extremely limited...

**Comment by andrethomas** [comment]
By all means, create a new branch of your code and type away... that's what github is all about. Take a look at how it may be done, for example in xdrv_12_home_assistant.ino look at void HAssDiscoverRelay() and how MqttPublish(stopic, true); was used... that would be a good starting point I think. Most of this is standard C by the way... only place where C++ is being used is in classes.

**Comment by andrethomas** [comment]
Just a note on creating your own branch...

image

Perhaps important, try keep your changes so that changes from the origin branch may still be applied if new features are added upstream from your branch.

You will see usually when new stuff is published to the main Tasmota development branch I pull them through to my development branch and to my mcp230xx_output branch.

That way I can enjoy the benefits of other people's code in my own branches.

When you clone your new branch, from command line

git clone -b branchname https://location.../......git foldername

When you've made changes, from inside the folder
git commit * -v -m "Comment on the changes you made"
git push

**Comment by MadDoct** [comment]
Thank you for all the tips, but maybe I gave you the wrong impression...
When I said "my C++ skills are extremely limited", what I really meant was
"my programming skills are extremely limited"... :/

A segunda, 6/08/2018, 07:54, andrethomas <notifications@github.com>
escreveu:

**Pull request merged**
