### PR TITLE
Increase readability even more

### PR DESCRIPTION
**Pull request by MadDoct**
Changed 0 with OFF and 1 with ON in most of the output.

This was my first "real coding", so please evaluate the changes...

### CODE REVIEW

**Comment by andrethomas** [comment]
Will test in mcp230xx_output branch first - do not want to commit to development at this stage.

**Comment by MadDoct** [comment]
Can you add an "inverted" flag so that, when you use active low relays, the command on will actually turn them on? Maybe you could take advantage of the sensor29 1,5,x command, given that the x (pull-up) isn't used in practice when using as output? 1 would be inverted and 0 would be normal...

**Comment by andrethomas** [comment]
The x part in your example is used to set the power-on/reset state if setoption0 is disabled in Tasmota firmware.

You can change b5 in settings if you want to implement an invert flag for a specific pin. If you look in the settings.h file you'll find the following:

```
typedef union {
  uint8_t data;
  struct {
    uint8_t pinmode : 3;                   // Pin mode (1 through 5)
    uint8_t pullup : 1;                    // Enable internal weak pull-up resistor
    uint8_t saved_state : 1;               // Save output state, if used.
    uint8_t b5 : 1;
    uint8_t b6 : 1;
    uint8_t b7 : 1;
  };
} Mcp230xxCfg;
```

b5,b6 and b6 bits are currently unused. Just be careful how you add the code to handle it as to note increase the codebase too much (compiled size, that is)

Another option could be to introduce pinmode 6 as an alternative to pinmode 5 - i.e. pinmode 5 could be normal operation whereas pinmode 6 could be interted operation.

In either of these approaches, it could be possible to configure a specific pin to be inverted instead of having an entire chip inverted.

mcp230xx_config[].pinmode is a 3 bit value so could store a value up to 7 (we currently use up to 5) so maybe not a bad idea to take that route.

If you want to experiment try both ways and see which one gives the best trade-off on compiled code size vs. usability/user-friendliness.

Best create a separate branch in your repo to play with these scenarios before randomly committing code :)

**Comment by MadDoct** [comment]
The problem is that my coding skills won't allow me to do that, probably...
Have you seen my recent commit? Is it OK?

andrethomas <notifications@github.com> escreveu no dia domingo, 12/08/2018
à(s) 18:31:

**Comment by andrethomas** [comment]
Your coding isn't that bad but you need to learn to compromise between resources on microcontrollers vs user friendly aspects... for example some of the changes you made to PROGMEM's is easier to read for a human, but takes more space in flash (compiled code) which leads to larger codebase required for driver... but one needs to strike a balance somewhere.

So maybe "C" is OK to mean COMMAND, but although smaller in flash it may be useful in some instances to send "COMMAND" back to user instead of sending "C".

Micro controllers require a slightly different approach to resource utilisation :)

Also, remember you do not need to make PR to me - you can make PR's directly to Tasmota's development branch.

**Comment by andrethomas** [comment]
Yes, I saw your recent commit - it was merged into my mcp230xx_output branch.

**Comment by MadDoct** [comment]
Ok, I implemented pinmode 6 amd am now testing... Will report back! ;)

**Comment by andrethomas** [comment]
Cool

I know there is a register for inverting behavior of the chip but I have not looked at how it works yet

**Comment by MadDoct** [comment]
Well, I did it using software...

A segunda, 13/08/2018, 13:51, andrethomas <notifications@github.com>
escreveu:

**Pull request merged**
