### PR TITLE
add pinmode 6 for inverted output and change output data some more...

### PR DESCRIPTION
**Pull request by MadDoct**

### CODE REVIEW

**Comment by andrethomas** [comment]
Testing OK

Only found 1 bug so far

tele/sonoff/SENSOR = {"Time":"2018-08-14T19:10:52","MCP230_OUT": {"OUT_D0":OFF,"OUT_D1

The ON and OFF should be text JSON.. i.e. "ON" and "OFF"

:)

**Comment by MadDoct** [comment]
Ok. I didn't change that... It was probably there before. Anyway, pinmode 6
seems to be working, right? ;)

A terça, 14/08/2018, 18:13, andrethomas <notifications@github.com> escreveu:

**Comment by andrethomas** [comment]
This is where you changed it :)

image

**Comment by andrethomas** [comment]
Cool

I saw you did a second PR - remember when you have an existing open PR any changes you commit is added to the open PR so the fix you did automatically included in this one when you pushed it.

**Comment by MadDoct** [comment]
Ah! OK, you are right, as usual! ;)

A terça, 14/08/2018, 18:34, andrethomas <notifications@github.com> escreveu:

**Comment by andrethomas** [comment]
Cool, no sweat.. you want to add a reset6 to go with all your changes? :)

**Pull request merged**
